# Lists and dictionaries

In [2]:
# A list is an ordered sequence of elements:
mylist = ['cat', 'window', 3]  # remember numbering starts from 0
print(mylist[0]) # first element of the list

# A dictionary stores key–value pairs:
person = {'name': 'John', 'age': 35, 'city': 'Milan'}
print(person['name'])    # 'John'
print(person['age'])     # 35
print(person['city'])    # 'Milan'


cat
John
35
Milan


# Basic code control

In [3]:
# Fibonacci series: the sum of two elements defines the next
a, b = 0, 1
while a < 5:
    print(a)
    a, b = b, a+b
    

0
1
1
2
3


In [5]:
# Test
x = int(input("Please enter an integer: "))
if x < 0:
    print('Negative')
elif x == 0:
    print('Zero')
elif x == 1:
    print('One')
else:
    print('More')    
    

Please enter an integer:  2


More


In [6]:
# loop
words = ['cat', 'window', 'defenestrate']  # words is a list of strings and i an iterable
for w in words:
    print(w, len(w))    
    

cat 3
window 6
defenestrate 12


In [7]:
# range as iterable    
for i in range(5):  # range creates an iterable excuding the last
    print(i)    
    

0
1
2
3
4


# Functions

In [8]:
# Definition
def fib(n):    # write Fibonacci series less than n
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

# Now call the function we just defined:
fib(2000)


0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


# Module 

A module is simply a Python file (.py) that contains code such as functions, classes, or variables. All the codes of the course are organized in modules, or separate files so programs stay manageable.


# Classes

A class in Python is a blueprint (or template) for creating objects. It defines attributes (data) and methods (functions) that the objects created from it will have. For instance:


In [9]:
class Point:

    def __init__(self, x, y):   # initialisation
        self.x = x
        self.y = y

    def move(self, dx, dy):   # method
        self.x += dx
        self.y += dy

p=Point(1,2)
p.move(3, -1)
print(p.x, p.y)         


4 1


As we will very often define classes, we use *@dataclass* which is a *class decorator*, which is easier to use and interpret. This has many applications in *readgmsh*

In [9]:
from dataclasses import dataclass

@dataclass
class Point:
    x: int
    y: int

    def move(self, dx: int, dy: int):
        self.x += dx
        self.y += dy

p = Point(1, 2)
p.move(3, -1)
print(p.x, p.y)    # 4 1

4 1


# NumPy

NumPy is the standard library for numerical computing in Python. Its main advantages are speed, convenience, and powerful mathematical operations.
Here are the main reasons to use it.

1. Much faster than Python lists. NumPy arrays are stored in contiguous memory and implemented in optimized C code.
2. Vectorized operations. You can perform operations on an entire array without writing loops.
3. Multi-dimensional arrays. NumPy naturally handles matrices and higher-dimensional arrays.



In [10]:
import numpy as np

a = np.array([1, 2, 3, 4]) # defines first array
print(a[0:-2],': all entries from beginning to end excluding last two\n')  
print(a ** 2, ': squares all entries at once\n')  

b = np.array([5, 6, 7, 8]) # defines second array 
print(a @ b,': dot product\n') 
print(a * b, ': element-by-element multiplication\n') 

c = np.array([[1, 2, 3],
              [4, 5, 6]])  # (2x3) matrix
print(c[0][1],': generic element\n') 
print(c.shape,': dimensions of the matrix c\n')      

d = np.array([[2, 3],
              [5, 6]])  # (2x2) matrix

print(c.T @ d, 'matrix multiplcation between c tranposed and d\n')


[1 2] : all entries from beginning to end excluding last two

[ 1  4  9 16] : squares all entries at once

70 : dot product

[ 5 12 21 32] : element-by-element multiplication

2 : generic element

(2, 3) : dimensions of the matrix c

[[22 27]
 [29 36]
 [36 45]] matrix multiplcation between c tranposed and d

